### ISSUE TITLE
Use of session.hash_function Can Cause 'Valid CSRF Token Required Error'

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket-1.7#247]
**UPDATE:  Changing directive may create larger hash causing session ID to be truncated in database. Leave directive blank until patch is committed.**

I get a "Valid CSRF Token Required" error when I try to login to SCP for the first time. This is a fresh install bleeding edge, deleted all files, removed database contents, chmod config file.

I run the install script and everything works and it confims all was successful. But when I go to login for the first time I get the above error. The login is correct because if I try to login with non-existant username it says invalid login, if I try  to login with wrong password it says invalid login. But when I login with correct info all I get is a blank page with the above. I do have cookies including 3rd party cookies enabled.

The CSRF token is being sent in form, I did notice the following HTML error:
&lt;input type="hidden" name="d"o value="scplogin"&gt; I assume you guys mean
&lt;input type="hidden" name="do" value="scplogin"&gt;

However changing the above HTML still yields the same error. What additional info do you guys need from me?

Also on a side-note I'm curious as to why you base64 encode a sha1 hash as it provides no additional security, and it makes it no safer to insert into HTML or or pass to requests:
$this->csrf['token'] = base64_encode(sha1(session_id().$r.SECRET_SALT));

**Comment by ghost** [comment]
So I did the following:

```
        $this->csrf['token'] = base64_encode(sha1(session_id().$r.SECRET_SALT));
        $this->csrf['time'] = time();
    echo $this->csrf['token']; // Output The Token Being Generated
```

The token is changing for each page request. That should not be the case. It should be static and tied to the session id. If the token changes for each request and someone say opens a link in new window the token on the current page will obviously become invalid since the new window has thus changed the token for the current session. Thus when I go to the login page the token outputed in the HTML is not the same token being compared to on the page the form is being submitted to reason why I am getting the error. Correct me if I am wrong on this, but I've done CSRF protection before based on OWASP guidelines and I've never come across software that changes the token on each request. If this is not the anticipated behavior then there is a bigger issue at hand.

https://owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#General_Recommendation:_Synchronizer_Token_Pattern
"In general, developers need only generate this token once for the current session."

**Comment by protich** [comment]
The system doesn't generate CSRF token for every page load as long as the session id doesn't change or the token is not expired. See `getToken` function in `include/class.csrf.php`. 

I can log in and out without any issues on my test installation.

**PS**. If you're getting a different token on every page load - as you indicated - then it could mean your session is somehow getting clobbered.

**Comment by ghost** [comment]
My session id is not changing per page request, but oddly the above token is changing in the echo statement above AND within the HTML form. Is there a specific session id name that is to be set? Maybe the correct one is not being set, I am having session_id set as it is what is specified in my php.ini file.

**Comment by protich** [comment]
Any data at all in `ost_session` table?

**Comment by ghost** [comment]
Yes, there are entries, I cleared them and and refreshed page and it created 1 entry, submitted form and it created another entry. Maybe my session id is being changed, at some point. This is my php.ini info for sessions http://pastebin.ws/cc1egr I've tried in multiple browsers in case its a browser issue.

**Comment by ghost** [comment]
You're right my session id is changing, but erratically so if I am on /scp/settings.php and refresh the page multiple times the id does not change. However if I submit the form on the page and the login.php page is then shown it changes my id, refreshing the login.php page changes my id on each page reload. Not sure why its only happening on that page.

Update: If I access login.php via GET it does not change the sid, if its via POST it changes the sid.

**Comment by protich** [comment]
osTicket overwrites default session handler to provide for ability to save session data into internal db table - as opposed to the file system. We also regenerate session ID upon successful login. Try commenting out the following block of code in `class.staff.php` and report the results.

``` php

session_regenerate_id(TRUE);
//Destroy old session ID - needed for PHP version < 5.1.0 TODO: remove when we move to php 5.3 as min. requirement.
if(($session=$ost->getSession()) && is_object($session) && $sid)
    $session->destroy($sid);
```

**Comment by ghost** [comment]
Same results, I assume the reason my sid changes when I submit the login POST is because it is a successful login, and ost is changing the sid then. I am still getting the CSRF error. My sid and token is being put into the database so that part works.

**Comment by protich** [comment]
Technically that shouldn't happen - with above code commented out. In fact, regenerating the sid simply changes the id not the data.

**Comment by ghost** [comment]
Doh I apologize, I didnt commeny out session_regenerate_id()

It is correctly updating the sid entry, but I still get the CSRF error.

**Comment by protich** [comment]
That is expected - does the new entry have session_data? If so - is the token correct?

**Comment by ghost** [comment]
The token is correct until I refresh the page. If I go to the /scp/ and check the sid and token it matches with what is in db, but refresh page the sid does not change, but the token does change on the HTML and in the db.

**Comment by ghost** [comment]
Interesting, now instead of refreshing if I submit the login the form the db entry changes from

csrf|a:2:{s:5:"token";s:56:"ZGRmZTVmZjllN2VlZTQ1ZGY5NWMxODg3ZGJiMDVkZTk1ODA3MjJjYQ==";s:4:"time";i:1346177812;}TZ_OFFSET|s:3:"0.0";TZ_DST|s:1:"0";_staff|a:1:{s:4:"auth";a:2:{s:4:"dest";s:37:"MY_SCP_PATH";s:3:"msg";s:23:"Authentication Required";}}

to

csrf|N;TZ_OFFSET|s:4:"-5.0";TZ_DST|b:0;_staff|a:2:{s:6:"userID";s:11:"MY_USERNAME";s:5:"token";s:76:"85d404a79b4bd8e6e5a14554d17107bc:1346177898:9f31ef43d846c3210d41405465a86a97";}

The sid stays the same.

**Comment by protich** [comment]
Interesting indeed. It seems like csrf is getting clobbered as I suspected. Do you happen to have global variables enabled?

**Comment by ghost** [comment]
http://pastebin.ws/78sg46 my php ini config, comments removed and alphabetized for your convenience.

**Comment by ghost** [comment]
Btw I am using PHP 5.4.5

**Comment by protich** [comment]
Register globals is no longer supported in PHP 5.4. Not sure what could be causing the issue - very interested in getting to the bottom of it. Would it be possible to get access to your installation + server? Let me know via peter at osticket dot com.

**Comment by ghost** [comment]
Emailed you, waiting for reply.

**Comment by ghost** [comment]
Any luck on finding the cause of this problem? Also, how did the you fare from the hurricane?

**Comment by ghost** [comment]
The problem seems to be in my php.ini settings. I deleted my custom file and I can now login, re-storing the file the problem comes back. I'll narrow down which setting is causing the problem and post it in shortly.

**Comment by ghost** [comment]
Found the the culprid:

session.auto_start = 0

Having that setting set to that value causes the CSRF issue, setting it to '1' the problem is fixed. =o) Might want to add some checks in the main.inc.php to override it if set to 0.

**Comment by protich** [comment]
That can't be the "real" cause. I have auto_start set to 0. 

We'll leave the issue open as we investigate further.

**Comment by ghost** [comment]
I dunno then, because I tested with it on and off and on again and off again and it seems to be what is causing the error to occur. I have cleared my cache as well. I literally deleted my php.ini file make a blank one with only the above setting and tested with it on and off. Well at least I got it working on my end =o) However the real issue will remain a mystery for awhile O.O

**Comment by ghost** [comment]
With default PHP settings and with the above setting set to 0 this is the output after trying to login:

Warning: date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /www/support/include/class.config.php on line 98

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /www/support/include/class.config.php:98) in /www/support/include/class.ostsession.php on line 39

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /www/support/include/class.config.php:98) in /www/support/include/class.ostsession.php on line 39

Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /www/support/include/class.staff.php on line 61

Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in /www/support/include/class.staff.php on line 583

Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /www/support/include/class.staff.php on line 61

Warning: date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /www/support/include/class.mailer.php on line 107

Warning: Cannot modify header information - headers already sent by (output started at /www/support/include/class.config.php:98) in /www/support/include/class.http.php on line 35

Warning: Cannot modify header information - headers already sent by (output started at /www/support/include/class.config.php:98) in /www/support/include/class.http.php on line 36

Warning: Cannot modify header information - headers already sent by (output started at /www/support/include/class.config.php:98) in /www/support/include/class.http.php on line 37

Warning: Cannot modify header information - headers already sent by (output started at /www/support/include/class.config.php:98) in /www/support/include/class.http.php on line 38

Warning: Cannot modify header information - headers already sent by (output started at /www/support/include/class.config.php:98) in /www/support/include/class.http.php on line 39
Valid CSRF Token Required

**Comment by ghost** [comment]
Keep in mind I am using no php.ini file other than a custom one with one line (the session auto-start setting) Also remember even when no data was being sent to browser from generated errors preventing the headers from being sent the CSRF error still was triggered.

**Comment by protich** [comment]
Thanks for the logs - very helpful. Try setting default timezone in php.ini e.g date.timezone = "US/Central"

**Comment by ghost** [comment]
Spoke too soon. date.timezone = "America/New_York" is what I already have in php.ini file and error still occurs. Tried even with US/Central doesnt work either.

**Comment by protich** [comment]
You still getting the date error log? Did you restart the web server?

**Comment by ghost** [comment]
It works when I put it by itself in an ini file, but in main ini it does not work. It doesn't look like it even gets set. I am going to examine my entire config file and see if there is some error somewhere that is causing the date setting to not load.

**Comment by protich** [comment]
You might want to examine `phpinfo()` output - to see effective php.ini file. You probably changing the wrong one.

PS. At least WE now know the real cause of the issue.

**Comment by protich** [comment]
We'll add `date_default_timezone_set("America/New_York");` setting to main.inc.php (before session start) as a fix for users who don't have permission to modify php.ini.

**Comment by ghost** [comment]
I verified with phpinfo() and the correct file is being modified and it is now showing up in the phpinfo() output but error still occurs.

**Comment by protich** [comment]
Try adding `date_default_timezone_set("America/New_York");` to main.inc.php around line 171.

**Comment by ghost** [comment]
Added, still get CSRF error.

**Comment by protich** [comment]
I'll sleep on it and revisit it tomorrow.

**Comment by ghost** [comment]
The thing is if I have a completely blank ini file and I do not add the above PHP line I can login. It still produces the timezone error, however I am still able to login.

**Comment by dozer55** [comment]
Do you have session.cookie_domain set in php.ini? This caused the CSRF error for me. Once I commented it out it worked fine. I'm running on RHEL6.

**Comment by Rubi08** [comment]
Thanks for this thread, I was having the same issue and changing the php.ini to reflect 'session.auto_start = 1' resolved it for me as well.

**Comment by ghost** [comment]
@dozer55 I used a blank php.ini file with only one setting. https://github.com/osTicket/osTicket-1.7/issues/247#issuecomment-8321492 Thus session.cookie_domain would be default core value of blank. I was able to enable and disable the error by changing that one value used in the file session.auto_start

@Rubi08 can you please post your php.ini file at http://pastebin.ws/ and provide us the link ('X' out any sensitive info before doing so). Also is there any way your setup is different from a typical install? I for instance use symlinks in webroot to point to corresponding install folder, and have permissions set to 701 for folders and 604 for files. Thanks.

I'd just love to figure out what is going on here. I don't want to use OST on my live server until I'm sure this bug is squashed and can ensure my staff/clients can login. Changing session.auto_start to 1 is just a band-aid fix, and does not resolve the real issue, since others can have it set to 0 and it works fine for them.

**Comment by protich** [comment]
I agree the issue is critical and needs to be addressed.

We narrowed down the issue to the cases where default timezone is not set in php.ini. This results in a warning error output on startup - which in turn causes session start in osTicket to fail. Setting `session.auto_start = 1` starts the session prior to the warning negating the issue. However, it's never a good idea to auto start the session.

**Comment by Rubi08** [comment]
@crypticmauler I tried to use pastebin but I get a 404 error. With that said, the php.ini file is the default one created by OS X 10.8 and it has a default time zone: date.timezone = "America/New_York" Nothing was edited in the file but the session.auto_start =.

@protich The time zone was set initially as it was there by default so does not seem to be the cause in my case.

**Comment by protich** [comment]
@Rubi08 - I was simply stating the issue as per @crypticmauler apache logs. Perhaps your issue is different - please check your logs for possible warnings and let us know.

**Comment by TechCare-Aus** [comment]
G'day guys, I am having the same issue after migrating to a new VPS. Is there a fix, was the problem identified?

Thanks,
Steven Swarts

**Comment by ghost** [comment]
@sjswarts85  the cause of the issue has not been determined. Adding the timezone in php.ini or directly in main.inc.php still caused the error. Changing the session autostart flag did fix it, but that should not be used and is just a band-aid fix since all it does it hide the real cause of the problem. Can you clear your PHP error logs and then then visit the login page and try to login so that the error is reproduced. Then check the logs and paste them here so we can see if there is any error occurring that is causing the headers to not be properly sent. Make sure you turn OFF session_autostart. Also if you can post your php.ini file with sensitive info X'ed out that will help as well.

**Comment by TechCare-Aus** [comment]
@crypticmauler yesterday I was running 1.7rc2 ... So I updated to 1.7rc3 and I haven't had that issue yet. Other issues have now arisen but I will post that in its appropriate place. 
If it comes back I'll post here.

**Comment by ghost** [comment]
I haven't updated to rc3, I'll update and see if the problem fixed itself.
I'm hoping it has so I can close this ticket. :)

**Comment by TechCare-Aus** [comment]
Well for me when I created a ticket I would test it just in case (being a release candidate). Anyway the first try would send an email to me (admin) with this error. However if I just tried again it would work. 
With RC3 it worked straight away no error, no email. 
Remember to clean your cache as well, because I had issues with not being able to delete a file (closed bug - https://github.com/osTicket/osTicket-1.7/issues/349)

**Comment by ghost** [comment]
Ok, I finally had time to upgrade to the latest build and the CSRF error still triggers when I try to login. Once again setting session.auto_start to 1 allows me to login. I produce no PHP errors before the change, after the change the only error I get is:

Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /main.inc.php on line 34...which we know is being caused by the session auto starting.

So still no idea what is causing this. No other errors are being produced so not timezone issue, since that is set and does not cause any errors. (checked PHP log).  Even when I override OSTs error_reporting setting in main.inc.php to E_ALL and get dozens of notice errors I can still login with auto_start on.

**Comment by TechCare-Aus** [comment]
Might  be a dumb comment, but have you tried installing 1.7rc3 on another virtual machine in a test environment? At the very least that will tell you if its osTicket or something on your system.

**Comment by ghost** [comment]
I think I may have found the actual issue now...

Could someone test this for me:

``` ini
; Select a hash function for use in generating session ids.
; Possible Values
;   0  (MD5 128 bits)
;   1  (SHA-1 160 bits)
; This option may also be set to the name of any hash function supported by
; the hash extension. A list of available hashes is returned by the hash_algos()
; function.
; http://php.net/session.hash-function
session.hash_function = "sha256"
```

the above causes the CSRF error. It is a valid value to put in there since sha256 is listed by hash_algos(), if I change the directive to:

``` ini
session.hash_function =
```

I can login fine, and not have to enable auto-sessions, my session even shows up in the database correctly =o). Can anyone confirm this behavior on their setup? Hopefully this was the cause otherwise I'm going to cry for wasting 3 hours =o\

**Comment by greezybacon** [comment]
Do you have suhosin built into your PHP by chance?

**Comment by ghost** [comment]
The problem was the above directive.

``` php
    function regenerate_id(){
        $oldId = session_id();
        session_regenerate_id();
        $this->destroy($oldId);
    }
```

This is my explanation as to why that directive causes the CSRF error. OST uses PHP's built in session_id() to create a session ID. I changed the default 32-char size session generation to something  that generates a hash larger than 32-chars. However, by using the above code OST then began using the SHA256 generated hash, yet in the CSRF code was comparing it to a 32-char size hash since the database field is set to varchar(32) so was being truncated. My cookie being set would never match the SID in database, reason why using session_start() worked since it would override the OST session class. So basically OST is hardcoded to only accept session ids that are 32-chars in size, anyone changing the above directive to create larger hashes would get CSRF error.

**Comment by greezybacon** [comment]
@protich, we should change the field size to `varchar(256)` which would support up to a 1024-bit hash

**Comment by ghost** [comment]
I changed my directive back to sha256 and changed fieldtype to varchar(256). I can confirm that change will fix the issue.

**Comment by greezybacon** [comment]
Could we drop the base64_encode from this line

``` php
$this->csrf['token'] = base64_encode(sha1(session_id().$r.SECRET_SALT));
```

It originally looked like

``` php
$this->csrf['token'] = base64_encode($r);
```

where `$r` was random 8-bit characters; however, after adding the extra entropy and wrapping in a sha1 hash, the base64 encoding is now unnecessary

**Comment by protich** [comment]
@crypticmauler  - Thanks you for the feedback.

@greezybacon - based on the discussions above - I think the issue is related to [hash function](http://php.net/session.hash-function) and the resulting session id. We have the session id field as varchar(32) - which can cause session start/loading problem **if** the length of the session id is greater than 32.

**Comment by protich** [comment]
Tested `hash('sha256', 'password');` and the resulting length is 64 chars.

**Comment by mirekh** [comment]
But this bug still active in version osTicket v1.7.1- "Stable" Release (September 03, 2013)

**Comment by greezybacon** [comment]
@mirekh, what version is reported in the admin panel for you install. Since we had an alarming number of reports of this bug since we released 1.7.1, we made several releases since. The version posted yesterday, which made another attempt to address the issue, is labeled 1.7.1.2

**Comment by mirekh** [comment]
I tried the version 1.7.1.2 (developed ver) - unchanged, bug still blocking me at the login page. :/
Mayby is simple method to block these feature? I don't really need this one (csrf['token']).
I just wanted to try out the application, or mayby add something to it.

**Comment by ghost** [comment]
@mirekh have you checked to make sure the database table was updated to allow the longer hashs? Also make sure you clear your cache/cookies and to be safe clear the sessions table. Also not to sound obvious make sure your cookie is being set by checking your response and request headers.

**Comment by mirekh** [comment]
I do not think....

**Comment by mirekh** [comment]
Cookies cleaned. But what about with "the database table was updated to allow the longer hashs"? What can I do with this? Which table & field may I change?

**Comment by TechCare-Aus** [comment]
@mirekh - try this (PLEASE NOTE THIS WORKED FOR ME, BUT MIGHT NOT WORK FOR YOU!!)

BACKUP BACKUP BACKUP!!! - copy your web files and your database (I use phpmyadmin for database)

1) Got to https://github.com/osTicket/osTicket-1.7/tree/develop and download as zip file or direct to your web hosting/server (If you choose that make sure you update permissions - chmod and/or chown, etc

2) I used the download to desktop ability, unpack, open filezilla (or whatever) and upload to your website - in my case I use this convention...

> ../support = soft link to latest osticket files
> ../osticket = working version - stable
> ../osticket-new = testing version
> ../osticket-old = old working stable

So in this case I uploaded everything into ../osticket-new

3) Edit your database - I used phpmyadmin - and navigate to your osticket database 

osticket --> ost_session

at the top of phpmyadmin there is a empty button - CRITICAL !! - make sure the page says you have open the ost_session table (otherwise you risk losing all)

Click on the Empty button, and then click Yes I think, can't remember.
Should show you a empty table

4) Remove cache from your web browser

5) Navigate to your osticket web folder - in my case http://example.com/osticket-new

Now CSS is working, I can see everything properly, looks great.

6) Navigate to osticket admin page - in my case http://example.com/osticket-new/scp

Log in, and check your version in Admin Panel --> Settings --> System Preferences - my states 1.7.0+

7) Optional - I then make a new soft link to the osticket-new and now clients/customers/staff and myself can access via http://example.com/support or http://example.com/support/scp

8) Optional - I keep it on osticket-new for awhile until I don't hear any complaints, then I move it back to standard setup. osticket-new becomes osticket, osticket becomes osticket-old, osticket-old is removed.

Hopefully that helps mate, I'm a newb but if I can I'll help :)

Regards,
Steve

**Comment by mirekh** [comment]
Thanks @sjswarts85. I try it soon.
