### ISSUE TITLE
Auto-assignment responder %{message} variable

### ISSUE THREAD

**Issue by drewx0r** [osTicket/osTicket-1.7#455]
The %{message} variable doesn't work when a ticket filter causes a new ticket to be auto-assigned. (just displays %{message})

**Comment by protich** [comment]
What version are you using? I think the issue was fixed in RC4 - upgrade or simply change `%{message}` to `%{comments}`.

**Comment by drewx0r** [comment]
I have RC4. I've changed the variable to `%{comments}` for now, but I don't understand why `%{message}` still doesn't work for me. Maybe something went a bit wonky in my upgrade.

**Comment by protich** [comment]
`%{message}` is not longer supported variable on assignment - it was changed to `%{comments}`. Commit f64242  included a DB patch to fix it on upgrade. 

Did you upgrade from RC3 or a new RC4 install?

**Comment by drewx0r** [comment]
RC3 -> RC4 upgrade.
