### ISSUE TITLE
Staff Login

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket-1.7#672]
Installed the new os Ticket 1.7.1 when logging in control panel it gives an error valid csrf required. This is a fresh install. Any solutions

**Comment by sabas** [comment]
@greezybacon same problem as mine in #653 , I can reproduce in a plain installation.

**Comment by greezybacon** [comment]
@merali780, @sabas, would either of you be available and willing to do a screencast session with me -- perhaps with TeamViewer or GoToMeeting? I haven't been able to reproduce the CSRF token issue.

**Comment by sabas** [comment]
@greezybacon also #677. Sorry I can't do screencast here at work, but I could try if I replicate the error at home. (Or if you want to try directly something drop me an email or an Hangouts chat, I have them open.

**Comment by greezybacon** [comment]
@merali780, are you accessing the osTicket installation on localhost by chance?

**Comment by pedronoliveira** [comment]
Having the exact same error on a localhost test instalation, tested with localhost address and throught other workstation on the same network as my localhost throught private IP, still get the same error.

EDIT: Just tested the same setup on my private VPS ArchLinux Lighttpd Mysql and it works normally

**Comment by jimmyeao** [comment]
im having this issue on a site I have tried to upgrade from 1.6 - running on Apache2.2.22 under debian in a VM. PHP Version 5.4.4-14+deb7u2 MySQL client version: 5.5.31
So far have tried to access via localhost, private ip, DNS name
Have downloaded the latest 1.7 dev release, still no joy..

**Comment by greezybacon** [comment]
@jimmyeao there was another issue concerning the detection of the URL path for the osTicket install -- #716. It was merged today. Would you mind trying again? We pushed the version out to the osticket.com site, so you could re-download it if you would like.

**Comment by jimmyeao** [comment]
Still have the same error... I installed the Dev version and the version of the osticket site to be sure...
I did notice a new requirement to install php-pear when installed the dev release

**Comment by jimmyeao** [comment]
Happy to do a remote session tomorrow around this time if that would help?

**Comment by greezybacon** [comment]
@jimmyeao, sorry about the php-pear issue. It was a mistake on our part. It is definitely not required. We've addressed that this week in the develop branch and in a new release

**Comment by greezybacon** [comment]
Can anyone / everyone verify that this is fixed with the tip of the develop branch and in osTicket 1.7.1.4?

**Comment by andresadanmx** [comment]
I installed os Ticket 1.7.1.4 in Centos with cPanel, when i logging in control panel it give me this error: Valid CSRF Token Required.
I searched a lot about a solution, but have not found something that works for me
